## Import Libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

## Load Dataset

In [4]:
df = pd.read_csv("emi_prediction_dataset.csv")

print(df.shape)

df.head()

C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\430840392.py:1: DtypeWarning: Columns (0: age) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("emi_prediction_dataset.csv")

(404800, 27)

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,other_monthly_expenses,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,38.0,Female,Married,Professional,82600.0,Private,0.9,Mid-size,Rented,20000.0,3,2,0.0,0.0,7200.0,19500.0,13200.0,Yes,23700.0,660.0,303200.0,70200.0,Personal Loan EMI,850000.0,15,Not_Eligible,500.0
1,38.0,Female,Married,Graduate,21500.0,Private,7.0,MNC,Family,0.0,2,1,5100.0,0.0,1400.0,5400.0,3500.0,Yes,4100.0,714.0,92500.0,26900.0,E-commerce Shopping EMI,128000.0,19,Not_Eligible,700.0
2,38.0,Male,Married,Professional,86100.0,Private,5.8,Startup,Own,0.0,4,3,0.0,0.0,10200.0,19400.0,6000.0,No,0.0,650.0,672100.0,324200.0,Education EMI,306000.0,16,Eligible,27775.0
3,58.0,Female,Married,High School,66800.0,Private,2.2,Mid-size,Own,0.0,5,4,11400.0,0.0,6200.0,11900.0,7900.0,No,0.0,685.0,440900.0,178100.0,Vehicle EMI,304000.0,83,Eligible,16170.0
4,48.0,Female,Married,Professional,57300.0,Private,3.4,Mid-size,Family,0.0,4,3,9400.0,21300.0,3600.0,16200.0,8100.0,No,0.0,770.0,97300.0,28200.0,Home Appliances EMI,252000.0,7,Not_Eligible,500.0

## Dataset Overview

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 404800 entries, 0 to 404799
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   age                     404800 non-null  object
 1   gender                  404800 non-null  str
 2   marital_status          404800 non-null  str
 3   education               402396 non-null  str
 4   monthly_salary          404800 non-null  str
 5   employment_type         404800 non-null  str
 6   years_of_employment     404800 non-null  float64
 7   company_type            404800 non-null  str
 8   house_type              404800 non-null  str
 9   monthly_rent            402374 non-null  float64
 10  family_size             404800 non-null  int64
 11  dependents              404800 non-null  int64
 12  school_fees             404800 non-null  float64
 13  college_fees            404800 non-null  float64
 14  travel_expenses         404800 non-null  float64
 15  groceries_utilities     404800 non-null  float64
 16  other_monthly_expenses  404800 non-null  float64
 17  existing_loans          404800 non-null  str
 18  current_emi_amount      404800 non-null  float64
 19  credit_score            402380 non-null  float64
 20  bank_balance            402374 non-null  str
 21  emergency_fund          402449 non-null  float64
 22  emi_scenario            404800 non-null  str
 23  requested_amount        404800 non-null  float64
 24  requested_tenure        404800 non-null  int64
 25  emi_eligibility         404800 non-null  str
 26  max_monthly_emi         404800 non-null  float64
dtypes: float64(12), int64(3), object(1), str(11)
memory usage: 117.3+ MB

## Missing Values

In [6]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": round(df.isnull().mean()*100,2)
})

missing.sort_values(
    by="Missing Values",
    ascending=False
)

                        Missing Values  Percentage
monthly_rent                      2426        0.60
bank_balance                      2426        0.60
credit_score                      2420        0.60
education                         2404        0.59
emergency_fund                    2351        0.58
marital_status                       0        0.00
monthly_salary                       0        0.00
years_of_employment                  0        0.00
gender                               0        0.00
employment_type                      0        0.00
age                                  0        0.00
family_size                          0        0.00
house_type                           0        0.00
company_type                         0        0.00
dependents                           0        0.00
groceries_utilities                  0        0.00
school_fees                          0        0.00
college_fees                         0        0.00
travel_expenses                      0        0.00
current_emi_amount                   0        0.00
existing_loans                       0        0.00
other_monthly_expenses               0        0.00
emi_scenario                         0        0.00
requested_amount                     0        0.00
requested_tenure                     0        0.00
emi_eligibility                      0        0.00
max_monthly_emi                      0        0.00

## Duplicate Records

In [7]:
duplicates = df.duplicated().sum()

print("Duplicate Records:", duplicates)

Duplicate Records: 0

## Fix Datatypes

In [8]:
object_cols = df.select_dtypes(include="object").columns

object_cols

C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\3816059625.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df.select_dtypes(include="object").columns

Index(['age', 'gender', 'marital_status', 'education', 'monthly_salary',
       'employment_type', 'company_type', 'house_type', 'existing_loans',
       'bank_balance', 'emi_scenario', 'emi_eligibility'],
      dtype='str')

In [9]:
df["monthly_salary"].head()

0    82600.0
1    21500.0
2    86100.0
3    66800.0
4    57300.0
Name: monthly_salary, dtype: str

In [10]:
df["monthly_salary"] = (
    df["monthly_salary"]
    .astype(str)
    .str.replace(",", "")
)

In [11]:
df["monthly_salary"] = pd.to_numeric(
    df["monthly_salary"],
    errors="coerce"
)

In [12]:
numeric_columns = [
    "bank_balance",
    "emergency_fund",
    "monthly_rent",
    "credit_score"
]

for col in numeric_columns:
    
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(",", "")
    )
    
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 404800 entries, 0 to 404799
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   age                     404800 non-null  object
 1   gender                  404800 non-null  str
 2   marital_status          404800 non-null  str
 3   education               402396 non-null  str
 4   monthly_salary          402807 non-null  float64
 5   employment_type         404800 non-null  str
 6   years_of_employment     404800 non-null  float64
 7   company_type            404800 non-null  str
 8   house_type              404800 non-null  str
 9   monthly_rent            402374 non-null  float64
 10  family_size             404800 non-null  int64
 11  dependents              404800 non-null  int64
 12  school_fees             404800 non-null  float64
 13  college_fees            404800 non-null  float64
 14  travel_expenses         404800 non-null  float64
 15  groceries_utilities     404800 non-null  float64
 16  other_monthly_expenses  404800 non-null  float64
 17  existing_loans          404800 non-null  str
 18  current_emi_amount      404800 non-null  float64
 19  credit_score            402380 non-null  float64
 20  bank_balance            400408 non-null  float64
 21  emergency_fund          402449 non-null  float64
 22  emi_scenario            404800 non-null  str
 23  requested_amount        404800 non-null  float64
 24  requested_tenure        404800 non-null  int64
 25  emi_eligibility         404800 non-null  str
 26  max_monthly_emi         404800 non-null  float64
dtypes: float64(14), int64(3), object(1), str(9)
memory usage: 111.5+ MB

In [19]:
num_cols = df.select_dtypes(
    include=["int64","float64"]
).columns

for col in num_cols:
    df[col].fillna(
        df[col].median(),
        inplace=True
    )

C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\1260991901.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(

In [15]:
cat_cols = df.select_dtypes(
    include="object"
).columns

for col in cat_cols:
    df[col].fillna(
        df[col].mode()[0],
        inplace=True
    )

C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\798516623.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(
C:\Users\Abarna Studio\AppData\Local\Temp\ipykernel_10504\798516623.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(

In [21]:
df.isnull().sum()

age                          0
gender                       0
marital_status               0
education                 2404
monthly_salary            1993
employment_type              0
years_of_employment          0
company_type                 0
house_type                   0
monthly_rent              2426
family_size                  0
dependents                   0
school_fees                  0
college_fees                 0
travel_expenses              0
groceries_utilities          0
other_monthly_expenses       0
existing_loans               0
current_emi_amount           0
credit_score              2420
bank_balance              4392
emergency_fund            2351
emi_scenario                 0
requested_amount             0
requested_tenure             0
emi_eligibility              0
max_monthly_emi              0
dtype: int64

In [22]:
# Numerical columns

num_cols = [
    'age',
    'monthly_salary',
    'years_of_employment',
    'monthly_rent',
    'school_fees',
    'college_fees',
    'travel_expenses',
    'groceries_utilities',
    'other_monthly_expenses',
    'current_emi_amount',
    'credit_score',
    'bank_balance',
    'emergency_fund',
    'requested_amount',
    'requested_tenure',
    'max_monthly_emi'
]

# Convert age first

df['age'] = pd.to_numeric(df['age'], errors='coerce')

# Fill numeric columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

# Categorical columns

cat_cols = [
    'gender',
    'marital_status',
    'education',
    'employment_type',
    'company_type',
    'house_type',
    'existing_loans',
    'emi_scenario',
    'emi_eligibility'
]

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [23]:
df.isnull().sum().sum()

np.int64(0)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 404800 entries, 0 to 404799
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   age                     404800 non-null  float64
 1   gender                  404800 non-null  str
 2   marital_status          404800 non-null  str
 3   education               404800 non-null  str
 4   monthly_salary          404800 non-null  float64
 5   employment_type         404800 non-null  str
 6   years_of_employment     404800 non-null  float64
 7   company_type            404800 non-null  str
 8   house_type              404800 non-null  str
 9   monthly_rent            404800 non-null  float64
 10  family_size             404800 non-null  int64
 11  dependents              404800 non-null  int64
 12  school_fees             404800 non-null  float64
 13  college_fees            404800 non-null  float64
 14  travel_expenses         404800 non-null  float64
 15  groceries_utilities     404800 non-null  float64
 16  other_monthly_expenses  404800 non-null  float64
 17  existing_loans          404800 non-null  str
 18  current_emi_amount      404800 non-null  float64
 19  credit_score            404800 non-null  float64
 20  bank_balance            404800 non-null  float64
 21  emergency_fund          404800 non-null  float64
 22  emi_scenario            404800 non-null  str
 23  requested_amount        404800 non-null  float64
 24  requested_tenure        404800 non-null  int64
 25  emi_eligibility         404800 non-null  str
 26  max_monthly_emi         404800 non-null  float64
dtypes: float64(15), int64(3), str(9)
memory usage: 111.5 MB

In [25]:
df.to_csv(
    "emi_cleaned.csv",
    index=False
)

print("Cleaned dataset saved")

Cleaned dataset saved

In [26]:
quality_report = pd.DataFrame({
    "Rows":[df.shape[0]],
    "Columns":[df.shape[1]],
    "Missing Values":[df.isnull().sum().sum()],
    "Duplicate Rows":[df.duplicated().sum()]
})

quality_report

     Rows  Columns  Missing Values  Duplicate Rows
0  404800       27               0               0